---
title: "wisconsin"
output: github_document
---
Section 1
```{r}
wisc.df <- read.csv("https://bioboot.github.io/bimm143_W18/class-material/WisconsinCancer.csv")
wisc.data <- as.matrix(wisc.df[,3:32]) # stores variables in columns 3-32 of wisc.df
row.names(wisc.data) <- wisc.df$id # assigns row names of wisc.data in 'id' column of wisc.df
diagnosis <- as.numeric(wisc.df$diagnosis == "M") # makes a vector and assings '1' to "M"
table(diagnosis) # 569 observations, 212 malignant diagnosis
x <- length(grep("_mean", colnames(wisc.data))) # 10 features suffixed with "_mean"
```
There are `r x` mean measurements in this data

Section 2
```{r}
colMeans(wisc.data) # finds means of columns
apply(wisc.data,2,sd) # finds standard deviations
wisc.pr <- prcomp(wisc.data, scale=TRUE) # performs PCA
summary(wisc.pr)
biplot(wisc.pr)
plot(wisc.pr$x[,c(1,2)], col=(diagnosis+1), xlab="PC1", ylab="PC2")
plot(wisc.pr$x[,c(1,3)], col=(diagnosis+1), xlab="PC1", ylab="PC3")
pr.var <- wisc.pr$sdev^2
pve <- pr.var / sum(pr.var)
plot(pve, xlab = "Principal Component", 
     ylab = "Proportion of Variance Explained", 
     ylim = c(0, 1), type = "o")
barplot(pve, ylab = "Percent of Variance Explained",
     names.arg=paste0("PC",1:length(pve)), las=2, axes = FALSE)
axis(2, at=pve, labels=round(pve,2)*100 )
plot(cumsum(pve), xlab = "Principal Component", 
     ylab = "Cumulative Proportion of Variance Explained", 
     ylim = c(0, 1), type = "o")
```

Section 3
```{r}
data.scaled <- scale(wisc.data)
data.dist <- dist(data.scaled)
wisc.hclust <- hclust(data.dist, method="complete")
plot(wisc.hclust)
wisc.hclust.clusters <- cutree(wisc.hclust, k=4)
table(wisc.hclust.clusters, diagnosis)
```

Section 4
```{r}
wisc.km <- kmeans(wisc.data, centers=2, nstart=20)
table(diagnosis, wisc.km$cluster)
table(wisc.hclust.clusters, wisc.km$cluster)
```

Section 5
```{r}
d.pr <- dist(wisc.pr$x[,1:7])
wisc.pr.hclust <- hclust(d.pr, method="complete")
wisc.pr.hclust.clusters <- cutree(wisc.pr.hclust, k=4)
table(wisc.pr.hclust.clusters, diagnosis)
```

Bonus section
```{r}
url <- "https://tinyurl.com/new-samples-CSV"
new <- read.csv(url)
npc <- predict(wisc.pr, newdata=new)
plot(wisc.pr$x[,1:2], col=(diagnosis+1))
points(npc[,1], npc[,2], col="blue", pch=16, cex=3)
```

